### your site title here

title: Jungi Kim
description: NLP Researcher

baseurl: "" #name of GitHub repository
url: "" #custom url to be used instead of GitHub repository
email: jungi.kim@gmail.com

# Pagination
# paginate: 4
# permalink: /blog/:year/:title/
# paginate_path: /blog/page:num/

# Social media links in footer
linkedin: "kimjungi"
github: "jungikim"
google_scholar: "Z34FcrEAAAAJ"
orcid: "0000-0002-4429-0981"
flickr: "yangpa"
google_analytics: "G-1BXBN4LBGQ"
#twitter: "#"
#quora: "#"
#instagram: "#"
#facebook: "#"
#researchgate: "#"
#stackoverflow: "#"

# Markdown
highlighter: rouge
markdown: kramdown

# Tracker
analytics:

# optimization -> compress.html
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []

#collection
#collections:
#  projects:
#    output: true
#    permalink: /projects/:name/
#    order:
#      - ASLEnMT.md
#      - shortProject.md
#      - longerProjectTitle.md
#      - redirect.md
#      - project4.md
#      - project5.md
#      - project6.md

sass:
  sass_dir: /assets/css/_sass
  style: compressed

include:
  - _pages

exclude:
  - README.md
  - LICENSE.md

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-email-protect
  - jekyll-target-blank
